name: "Update notion tasks"
description: "Automatically update notions tasks"
inputs:
  context:
    required: true
    type: string
  notionToken:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
  
  - uses: actions/checkout@v3
  
  - using: node16
    main: "index.js"
